ALTER TABLE sm_fills ALTER COLUMN oid DROP NOT NULL;

ALTER TABLE sm_fills ALTER COLUMN tid DROP NOT NULL;

ALTER TABLE sm_fills ALTER COLUMN fee DROP NOT NULL;

ALTER TABLE sm_fills ALTER COLUMN fee_token DROP NOT NULL
